fonctions: fonctions.o main.o
    gcc -o fonctions fonctions.o main.o -lSDL2 -lSDL2_image -lSDL2_ttf
fonctions.o: fonctions.c -lSDL2 -lSDL2_image -lSDL2_ttf
    gcc -o fonctions.o -c fonctions.c
main.o: main.c fonctions.h
    gcc -o main.o -c main.c -lSDL2 -lSDL2_image -lSDL2_ttf
